#!/usr/bin/env python
"""Generate traceable paper facts and LaTeX macros from final audited tables."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
MODEL_ORDER = ["CARDIAC-FM", "CSFM", "ECG-FM", "ECG-JEPA", "HuBERT-ECG", "ST-MEM"]
MODEL_MACROS = {
    "CARDIAC-FM": "Cardiac",
    "CSFM": "Csfm",
    "ECG-FM": "EcgFm",
    "ECG-JEPA": "EcgJepa",
    "HuBERT-ECG": "Hubert",
    "ST-MEM": "StMem",
}
METRICS = {
    "recon_R2": "Recon",
    "semantic_alignment": "Semantic",
    "concept_coverage_020": "Coverage",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT / "results/multiscale_sae_v1")
    parser.add_argument(
        "--sensitivity-root",
        type=Path,
        default=ROOT / "results/multiscale_sae_fixed_k_over_n_middepth_v1",
    )
    return parser.parse_args()


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".tmp.{os.getpid()}")
    tmp.write_text(text)
    os.replace(tmp, path)


def finite(value: Any) -> float:
    result = float(value)
    if not np.isfinite(result):
        raise ValueError(f"non-finite paper fact: {value}")
    return result


def main() -> None:
    args = parse_args()
    release = json.loads((args.root / "final_release_audit.json").read_text())
    if not release.get("audit_pass"):
        raise RuntimeError(f"final release audit must pass before paper facts: {release.get('errors')}")
    patient_audit = json.loads((args.root / "test_patient_bootstrap_audit.json").read_text())
    primary_audit = json.loads((args.root / "audit.json").read_text())
    operating_audit = json.loads((args.root / "operating_point_audit.json").read_text())
    sensitivity_audit = json.loads(
        (args.sensitivity_root / "test_sparsity_sensitivity_audit.json").read_text()
    )
    profiles = pd.read_csv(args.root / "test_patient_bootstrap_model_profiles.csv")
    pairs = pd.read_csv(args.root / "test_patient_bootstrap_model_pairs.csv")
    ranks = pd.read_csv(args.root / "test_patient_bootstrap_rank_probabilities.csv")
    design_rank = pd.read_csv(args.root / "test_scale_rank_stability.csv")
    stability = pd.read_csv(args.root / "stability_model_profiles.csv")
    sensitivity_rank = pd.read_csv(args.sensitivity_root / "test_sparsity_rank_agreement.csv")

    facts: dict[str, Any] = {
        "protocol": {
            "models": 6,
            "depths": 5,
            "expansions": [1, 4, 8, 16, 32],
            "seeds": 3,
            "cells": int(primary_audit["complete_cells"]),
            "matched_blocks": int(primary_audit["complete_matched_blocks"]),
            "patients": int(patient_audit["n_patients"]),
            "bootstrap_samples": int(patient_audit["bootstrap_samples"]),
            "concepts": int(patient_audit["concept_rows"] // 6),
        },
        "metrics": {},
        "stability": {},
        "sparsity_sensitivity": {},
        "stage_two_selection": {
            "points": int(operating_audit["selected_points"]),
            "checkpoints": int(operating_audit["selected_checkpoints"]),
            "selection_split": operating_audit["selection_split"],
            "test_metrics_used_for_selection": operating_audit["test_metrics_used_for_selection"],
        },
        "claim_rule": "metric-specific comparisons over identical E values; no composite or per-model best-scale ranking",
    }
    macro_lines = [
        "% Generated by scripts/make_multiscale_sae_paper_facts.py; do not edit manually.",
        r"\providecommand{\MSModels}{6}",
        r"\providecommand{\MSDepths}{5}",
        r"\providecommand{\MSScales}{5}",
        r"\providecommand{\MSSeeds}{3}",
        f"\\providecommand{{\\MSCells}}{{{facts['protocol']['cells']}}}",
        f"\\providecommand{{\\MSMatchedBlocks}}{{{facts['protocol']['matched_blocks']}}}",
        f"\\providecommand{{\\MSPatients}}{{{facts['protocol']['patients']:,}}}",
        f"\\providecommand{{\\MSBootstrapSamples}}{{{facts['protocol']['bootstrap_samples']:,}}}",
        f"\\providecommand{{\\MSConcepts}}{{{facts['protocol']['concepts']}}}",
    ]
    markdown = [
        "# Multi-Scale SAE Audited Paper Facts",
        "",
        "All model comparisons use the same relative expansion values. No fact below uses a per-model best SAE scale.",
        "",
        f"- Complete cells: {facts['protocol']['cells']}",
        f"- Complete six-model matched blocks: {facts['protocol']['matched_blocks']}",
        f"- Test patients: {facts['protocol']['patients']:,}",
        f"- Patient bootstrap samples: {facts['protocol']['bootstrap_samples']:,}",
        "",
    ]

    for metric, macro_metric in METRICS.items():
        metric_profiles = profiles[profiles.metric == metric].set_index("model").loc[MODEL_ORDER]
        metric_pairs = pairs[pairs.metric == metric]
        metric_ranks = ranks[
            (ranks.metric == metric) & (ranks.scope == "common_scale_auc")
        ].set_index("model").loc[MODEL_ORDER]
        order = metric_profiles.observed_common_scale_auc.sort_values(ascending=False).index.tolist()
        top_model = order[0]
        significant_pairs = int((metric_pairs.q_bh < 0.05).sum())
        scale_rows = design_rank[design_rank.metric == {
            "recon_R2": "reconstruction",
            "semantic_alignment": "semantic_alignment",
            "concept_coverage_020": "concept_coverage",
        }[metric]]
        metric_fact = {
            "order": order,
            "top_model": top_model,
            "significant_pairwise_contrasts_bh_005": significant_pairs,
            "median_cross_scale_kendall_tau": finite(scale_rows.kendall_tau.median()),
            "minimum_cross_scale_kendall_tau": finite(scale_rows.kendall_tau.min()),
            "models": {},
        }
        macro_lines.extend(
            [
                f"\\providecommand{{\\MS{macro_metric}TopModel}}{{{top_model}}}",
                f"\\providecommand{{\\MS{macro_metric}Order}}{{{' $>$ '.join(order)}}}",
                f"\\providecommand{{\\MS{macro_metric}SignificantPairs}}{{{significant_pairs}}}",
                f"\\providecommand{{\\MS{macro_metric}MedianScaleTau}}{{{metric_fact['median_cross_scale_kendall_tau']:.2f}}}",
                f"\\providecommand{{\\MS{macro_metric}MinScaleTau}}{{{metric_fact['minimum_cross_scale_kendall_tau']:.2f}}}",
            ]
        )
        markdown.extend(
            [
                f"## {metric}",
                "",
                f"- Common-scale order: {' > '.join(order)}",
                f"- BH-significant pairwise contrasts: {significant_pairs}/15",
                f"- Cross-scale Kendall tau: median {metric_fact['median_cross_scale_kendall_tau']:.3f}, minimum {metric_fact['minimum_cross_scale_kendall_tau']:.3f}",
                "",
                "| Model | Common-scale AUC | Patient 95% CI | P(rank 1) | Mean rank |",
                "|---|---:|---:|---:|---:|",
            ]
        )
        for model in MODEL_ORDER:
            row = metric_profiles.loc[model]
            rank = metric_ranks.loc[model]
            values = {
                "observed": finite(row.observed_common_scale_auc),
                "ci_low": finite(row.ci_low),
                "ci_high": finite(row.ci_high),
                "probability_rank_1": finite(rank.probability_rank_1),
                "mean_rank": finite(rank.mean_rank),
            }
            metric_fact["models"][model] = values
            prefix = f"MS{MODEL_MACROS[model]}{macro_metric}"
            macro_lines.extend(
                [
                    f"\\providecommand{{\\{prefix}AUC}}{{{values['observed']:.3f}}}",
                    f"\\providecommand{{\\{prefix}CILow}}{{{values['ci_low']:.3f}}}",
                    f"\\providecommand{{\\{prefix}CIHigh}}{{{values['ci_high']:.3f}}}",
                    f"\\providecommand{{\\{prefix}RankOne}}{{{values['probability_rank_1']:.3f}}}",
                    f"\\providecommand{{\\{prefix}MeanRank}}{{{values['mean_rank']:.2f}}}",
                ]
            )
            markdown.append(
                f"| {model} | {values['observed']:.3f} | "
                f"[{values['ci_low']:.3f}, {values['ci_high']:.3f}] | "
                f"{values['probability_rank_1']:.3f} | {values['mean_rank']:.2f} |"
            )
        top_values = metric_fact["models"][top_model]
        macro_lines.extend(
            [
                f"\\providecommand{{\\MS{macro_metric}TopAUC}}{{{top_values['observed']:.3f}}}",
                f"\\providecommand{{\\MS{macro_metric}TopCILow}}{{{top_values['ci_low']:.3f}}}",
                f"\\providecommand{{\\MS{macro_metric}TopCIHigh}}{{{top_values['ci_high']:.3f}}}",
                f"\\providecommand{{\\MS{macro_metric}TopRankOne}}{{{top_values['probability_rank_1']:.3f}}}",
            ]
        )
        markdown.append("")
        facts["metrics"][metric] = metric_fact

    stability = stability.set_index("model").loc[MODEL_ORDER]
    stability_order = stability.multiscale_stability_auc.sort_values(ascending=False).index.tolist()
    subspace_order = stability.multiscale_subspace_auc.sort_values(ascending=False).index.tolist()
    facts["stability"] = {
        "matched_cosine_above_random_order": stability_order,
        "subspace_overlap_order": subspace_order,
        "models": {},
    }
    macro_lines.extend(
        [
            f"\\providecommand{{\\MSStabilityTopModel}}{{{stability_order[0]}}}",
            f"\\providecommand{{\\MSSubspaceTopModel}}{{{subspace_order[0]}}}",
        ]
    )
    markdown.extend(["## Stability", "", f"- Above-random stability order: {' > '.join(stability_order)}", f"- Subspace-overlap order: {' > '.join(subspace_order)}", ""])
    for model in MODEL_ORDER:
        row = stability.loc[model]
        values = {
            "stability_auc": finite(row.multiscale_stability_auc),
            "subspace_auc": finite(row.multiscale_subspace_auc),
        }
        facts["stability"]["models"][model] = values
        prefix = f"MS{MODEL_MACROS[model]}"
        macro_lines.extend(
            [
                f"\\providecommand{{\\{prefix}StabilityAUC}}{{{values['stability_auc']:.3f}}}",
                f"\\providecommand{{\\{prefix}SubspaceAUC}}{{{values['subspace_auc']:.3f}}}",
            ]
        )
    top_stability = facts["stability"]["models"][stability_order[0]]
    top_subspace = facts["stability"]["models"][subspace_order[0]]
    macro_lines.extend(
        [
            f"\\providecommand{{\\MSStabilityTopAUC}}{{{top_stability['stability_auc']:.3f}}}",
            f"\\providecommand{{\\MSSubspaceTopAUC}}{{{top_subspace['subspace_auc']:.3f}}}",
        ]
    )

    for metric in sorted(sensitivity_rank.metric.unique()):
        rows = sensitivity_rank[sensitivity_rank.metric == metric]
        key = metric.replace("_", "-")
        facts["sparsity_sensitivity"][metric] = {
            "median_rank_kendall_tau": finite(rows.kendall_tau.median()),
            "minimum_rank_kendall_tau": finite(rows.kendall_tau.min()),
        }
        macro_name = "".join(part.title() for part in metric.split("_"))
        macro_lines.extend(
            [
                f"\\providecommand{{\\MS{macro_name}SparsityMedianTau}}{{{rows.kendall_tau.median():.2f}}}",
                f"\\providecommand{{\\MS{macro_name}SparsityMinTau}}{{{rows.kendall_tau.min():.2f}}}",
            ]
        )
        markdown.append(
            f"- Fixed-k/d versus fixed-k/N {key} rank tau: median "
            f"{rows.kendall_tau.median():.3f}, minimum {rows.kendall_tau.min():.3f}"
        )
    facts["sparsity_sensitivity"]["e8_anchor_max_abs_difference"] = finite(
        sensitivity_audit["e8_anchor_max_abs_difference"]
    )
    macro_lines.extend(
        [
            f"\\providecommand{{\\MSEightAnchorMaxDifference}}{{{sensitivity_audit['e8_anchor_max_abs_difference']:.4f}}}",
            f"\\providecommand{{\\MSSelectedPoints}}{{{facts['stage_two_selection']['points']}}}",
            f"\\providecommand{{\\MSSelectedCheckpoints}}{{{facts['stage_two_selection']['checkpoints']}}}",
        ]
    )
    markdown.extend(
        [
            "",
            f"- E=8 arm-anchor maximum absolute metric difference: {sensitivity_audit['e8_anchor_max_abs_difference']:.6f}",
            "",
            "## Stage-two validation selection",
            "",
            f"- Selected operating points: {facts['stage_two_selection']['points']}",
            f"- Selected checkpoints: {facts['stage_two_selection']['checkpoints']}",
            "- Test metrics used for selection: false",
        ]
    )

    atomic_text(args.root / "paper_facts.json", json.dumps(facts, indent=2) + "\n")
    atomic_text(args.root / "paper_macros.tex", "\n".join(macro_lines) + "\n")
    atomic_text(args.root / "paper_facts.md", "\n".join(markdown) + "\n")
    metadata = {
        "status": "complete",
        "release_audit_pass": True,
        "model_metrics": len(facts["metrics"]),
        "models": len(MODEL_ORDER),
        "composite_interpretability_score": False,
        "per_model_best_scale_ranking": False,
        "outputs": ["paper_facts.json", "paper_macros.tex", "paper_facts.md"],
    }
    atomic_text(args.root / "paper_facts_audit.json", json.dumps(metadata, indent=2) + "\n")
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
